# Generated by Django 6.0.1 on 2026-01-31 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0001_initial'),
        ('recipient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_dispatch', models.DateTimeField(blank=True, help_text='yyyy-mm-dd 00:00:00', null=True, verbose_name='Дата и время первой отправки')),
                ('end_dispatch', models.DateTimeField(blank=True, help_text='yyyy-mm-dd 00:00:00', null=True, verbose_name='Дата и время окончания отправки')),
                ('status', models.CharField(choices=[('CO', 'Завершена'), ('CR', 'Создана'), ('LA', 'Запущена')], default='CR', max_length=20, verbose_name='Статус')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='message.message', verbose_name='Сообщение')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailing_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('recipients', models.ManyToManyField(related_name='recipients', to='recipient.recipient', verbose_name='Получатели')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['status', 'first_dispatch', 'message'],
                'permissions': [('can_see_all_mailings', 'Can see all mailings'), ('can_cancel_mailing', 'Can cancel mailing')],
            },
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attempt', models.DateTimeField(help_text='yyyy-mm-dd 00:00:00', verbose_name='Дата и время попытки')),
                ('status', models.CharField(choices=[('SU', 'Успешно'), ('FA', 'Не успешно')], max_length=20, verbose_name='Статус')),
                ('mail_response', models.TextField(verbose_name='Ответ почтового сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_attempts', to='mailings.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
                'ordering': ['status', 'date_attempt'],
            },
        ),
    ]
