# Generated by Django 5.1.7 on 2025-03-31 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='end_dispatch',
            field=models.DateTimeField(help_text='yyyy-mm-dd 00:00:00', verbose_name='Дата и время окончания отправки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='first_dispatch',
            field=models.DateTimeField(help_text='yyyy-mm-dd 00:00:00', verbose_name='Дата и время первой отправки'),
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attempt',
                 models.DateTimeField(help_text='yyyy-mm-dd 00:00:00', verbose_name='Дата и время попытки')),
                ('status', models.CharField(choices=[('SU', 'Успешно'), ('FA', 'Не успешно')], max_length=20,
                                            verbose_name='Статус')),
                ('mail_response', models.TextField(verbose_name='Ответ почтового сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing',
                                              to='mailings.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
                'ordering': ['status', 'date_attempt'],
            },
        ),
    ]
