# Generated by Django 5.1.7 on 2025-04-04 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_alter_mailing_end_dispatch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['status', 'first_dispatch', 'message'],
                     'permissions': [('can_see_all_mailings', 'Can see all mailings')], 'verbose_name': 'Рассылка',
                     'verbose_name_plural': 'Рассылки'},
        ),
    ]
