# Generated by Django 5.1.7 on 2025-04-04 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0005_mailing_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingattempt',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_attempts',
                                    to='mailings.mailing', verbose_name='Рассылка'),
        ),
    ]
