# Generated by Django 5.1.7 on 2025-04-04 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ['full_name'], 'permissions': [('can_see_all_recipients', 'Can see all recipients')],
                     'verbose_name': 'Получатель', 'verbose_name_plural': 'Получатели'},
        ),
    ]
